spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSl=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
# 打印、格式化
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
#默认8080避免冲突
server:
  port: 8181
